version: "3.1"

volumes:
  mongo_data:
          
services:
  
  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db